export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_FEATURED_USERS = "SET_FEATURED_USERS";
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOG_OUT = "LOG_OUT";
export const ASYNC_START = "ASYNC_START";
export const SET_RELEVANT_UPDATES = "SET_RELEVANT_UPDATES";
export const HANDLE_SEARCH = "HANDLE_SEARCH";
export const SEARCH_VIEW = "SEARCH_VIEW";
export const UPDATES_VIEW = "UPDATES_VIEW";
export const INDIVIDUAL_CHARITY_VIEW = "INDIVIDUAL_CHARITY_VIEW";
export const RESET_SEARCH = "RESET_SEARCH";

